#!/bin/bash
apache=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
if [ $apache -eq 0 ] #apache puudumise korral installeerib
then
	echo "Apache2 install"
	apt install apache2 -y

elif [ $apache -eq 1 ]
then
	echo "Apache2 on paigaldatud"
	systemctl status apache2
fi
